spring:
  application:
    name: billing-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  datasource:
    driver-class-name: org.h2.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:/app/data/billingdb;DB_CLOSE_DELAY=-1}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
spring.h2.console.enabled: true
server:
  port: 8082

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8080}
membership-service:
  url: ${SUBSCRIPTION_SERVICE_URL:http://localhost:8081}
notification-service:
  url: ${NOTIFICATION_SERVICE_URL:http://localhost:8083}

logging:
  level:
    dre.billingservice: DEBUG
    dre.billingservice.client: DEBUG
    dre.billingservice.service.impl: DEBUG
    feign: DEBUG
    org.springframework.web: DEBUG
